config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: :all
  devise_scope :customer do
    get '/customers/sign_up' => 'public/registrations#new'
    post '/customers' => 'public/registrations#create'
    get '/customers/sign_in' => 'public/sessions#new'
    post '/customers/sign_in' => 'public/sessions#create'
    delete '/customers/sign_out' => 'public/sessions#destroy'
    patch '/customers/withdraw' => 'public/customers#withdraw'
  end

  devise_for :admin, controllers: {
    sessions: 'admin/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

# Admin
  get '/admin', to: 'admin/homes#top'

  namespace :admin do
    resources :items, except: [:destroy]
  end

  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update]
  end

  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
  end

# できたらやる
  namespace :admin do
    resources :orders, only: [:show, :update]
  end

  namespace :admin do
    get '/orders/:order_details/:id', to: 'admin/order_details#update'
  end

# 会員
  root to:'public/homes#top'
  get '/about', to:'public/homes#about'

  resources :items, only: [:index, :show], to: 'public/items#'

  resource :customers, only: [:edit, :update], to: 'public/customers#'
  get '/customers/my_page', to:'public/customers#show'
  get '/customers/unsubscribe', to:'public/customers#unsubscribe'

  delete '/cart_items/destroy_all', to:'public/cart_items#destroy_all'
  resources :cart_items, only: [:index, :update, :destroy, :create], to: 'public/cart_items#'

  get '/orders/complete', to: 'public/orders#complete'
  post '/orders/confirm', to: 'public/orders#confirm'
  resources :orders, only: [:new, :create, :index, :show], to: 'public/orders#'

  resources :addresses, except: [:show, :new], to: 'public/addresses#'

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  def active_for_authentication?
    super && (self.is_active == true)
  end

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name_kana, presence: true
  validates :last_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
  validates :email, presence: true
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers=Customer.page(params[:page]).reverse_order
  end

  def show
    @customer=Customer.find(params[:id])
  end

  def edit
    @customer=Customer.find(params[:id])
  end

  def update
    customer=Customer.find(params[:id])
    if customer.update(customer_params)
      redirect_to admin_customer_path
    else
      @customer=Customer.find(params[:id])
      render :edit
    end
  end

  private
  def customer_params
    params.require(:customer).permit(:id, :first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number, :email)
  end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<main>
  <div class="container">
    <% if @customer.errors.any? %>
      <%= @customer.errors.count %>件のエラーが発生しました
      <% @customer.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
    <% end %>
    <h3>
      <%=@customer.first_name%><%=@customer.last_name%>さんの会員情報編集
    </h3>
    <%=form_with model:@customer,url: admin_customer_path, local:true do |f| %>
      <table class="table table-borderless">
        <tr>
          <th>
            会員ID
          </th>
          <td>
            <%=@customer.id%>
          </td>
        </tr>
        <tr>
          <th>
            氏名
          </th>
          <td>
            <%= f.text_field :first_name %><%= f.text_field :last_name %>
          </td>
        </tr>
        <tr>
          <th>
            フリガナ
          </th>
          <td>
            <%= f.text_field :first_name_kana %><%= f.text_field :last_name_kana %>
          </td>
        </tr>
        <tr>
          <th>
            郵便番号
          </th>
          <td>
            <%= f.text_field :postal_code %>
          </td>
        </tr>
        <tr>
          <th>
            住所
          </th>
          <td>
            <%= f.text_field :address %>
          </td>
        </tr>
        <tr>
          <th>
            電話番号
          </th>
          <td>
            <%= f.text_field :telephone_number %>
          </td>
        </tr>
        <tr>
          <th>
            メールアドレス
          </th>
          <td>
            <%= f.text_field :email %>
          </td>
        </tr>
        <tr>
          <th>
            会員ステータス
          </th>
          <td>
            -
          </td>
        </tr>
      </table>
      <%= f.submit '変更を保存', class:"btn btn-success" %>
    <%end%>
  </div>
</main>

app/views/admin/customers/index.html.erb
<main>
  <div class="container">
    <h3>会員一覧</h3>
    <table class="table">
      <tr>
        <td>
          会員ID
        </td>
        <td>
          氏名
        </td>
        <td>
          メールアドレス
        </td>
        <td>
          ステータス
        </td>
      </tr>
      <%@customers.each do |customer|%>
      <tr>
        <td>
          <%=customer.id%>
        </td>
        <td>
          <%=link_to admin_customer_path(customer.id) do %>
            <%=customer.first_name%><%=customer.last_name%>
          <%end%>
        </td>
        <td>
          <%=customer.email%>
        </td>
        <td>
          <%=customer.is_active%>
        </td>
      </tr>
      <%end%>
    </table>
    <%= paginate @customers %>
  </div>
</main>

app/views/admin/customers/show.html.erb
<main>
  <div class="container">
    <h3>
      <%=@customer.first_name%><%=@customer.last_name%>さんの会員詳細
    </h3>
    <table class="table table-borderless">
      <tr>
        <th>
          会員ID
        </th>
        <td>
          <%=@customer.id%>
        </td>
      </tr>
      <tr>
        <th>
          氏名
        </th>
        <td>
          <%=@customer.first_name%><%=@customer.last_name%>
        </td>
      </tr>
      <tr>
        <th>
          フリガナ
        </th>
        <td>
          <%=@customer.first_name_kana%><%=@customer.last_name_kana%>
        </td>
      </tr>
      <tr>
        <th>
          郵便番号
        </th>
        <td>
          <%=@customer.postal_code%>
        </td>
      </tr>
      <tr>
        <th>
          住所
        </th>
        <td>
          <%=@customer.address%>
        </td>
      </tr>
      <tr>
        <th>
          電話番号
        </th>
        <td>
          <%=@customer.telephone_number%>
        </td>
      </tr>
      <tr>
        <th>
          メールアドレス
        </th>
        <td>
          <%=@customer.email%>
        </td>
      </tr>
      <tr>
        <th>
          会員ステータス
        </th>
        <td>
          <%=@customer.is_active%>
        </td>
      </tr>
    </table>
    <%=link_to '編集する', edit_admin_customer_path, class:"btn btn-success"%>
    <%=link_to '注文履歴一覧を見る', admin_path, class:"btn btn-primary"%>
  </div>
</main>