config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: :all
  devise_scope :customer do
    get '/customers/sign_up' => 'public/registrations#new'
    post '/customers' => 'public/registrations#create'
    get '/customers/sign_in' => 'public/sessions#new'
    post '/customers/sign_in' => 'public/sessions#create'
    delete '/customers/sign_out' => 'public/sessions#destroy'
    patch '/customers/withdraw' => 'public/customers#withdraw'
  end

  devise_for :admin, controllers: {
    sessions: 'admin/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

# Admin
  get '/admin', to: 'admin/homes#top'

  namespace :admin do
    resources :items, except: [:destroy]
  end

  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update]
  end

  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
  end

# できたらやる
  namespace :admin do
    resources :orders, only: [:show, :update]
  end

  namespace :admin do
    get '/orders/:order_details/:id', to: 'admin/order_details#update'
  end

# 会員
  root to:'public/homes#top'
  get '/about', to:'public/homes#about'

  resources :items, only: [:index, :show], to: 'public/items#'

  resource :customers, only: [:edit, :update], to: 'public/customers#'
  get '/customers/my_page', to:'public/customers#show'
  get '/customers/unsubscribe', to:'public/customers#unsubscribe'

  delete '/cart_items/destroy_all', to:'public/cart_items#destroy_all'
  resources :cart_items, only: [:index, :update, :destroy, :create], to: 'public/cart_items#'

  get '/orders/complete', to: 'public/orders#complete'
  post '/orders/confirm', to: 'public/orders#confirm'
  resources :orders, only: [:new, :create, :index, :show], to: 'public/orders#'

  resources :addresses, except: [:show, :new], to: 'public/addresses#'

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def full_address
    postal_code + address + name
  end

  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  def active_for_authentication?
    super && (self.is_active == true)
  end

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name_kana, presence: true
  validates :last_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
  validates :email, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre

  attachment :image

  validates :image, presence: true
  validates :name, presence: true
  validates :introduction, presence: true
  validates :genre_id, presence: true
  validates :price, presence: true


  def add_tax_price
    (self.price * 1.10).round
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum payment_method: { "クレジットカード": 0, "銀行振込": 1 }
  enum order_status: {"入金待ち": 0,"入金確認": 1,"製作中": 2,"発送準備中": 3, "発送済み": 4}

	def cart_items
		cart.line_items.each do |item|
			item.cart_item_id = nil
			line_items << item
		end
	end

	validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true
  validates :payment_method, presence: true

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item


end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genre=Genre.new
    @genres=Genre.all
  end

  def create
    genre=Genre.new(genre_params)
    if genre.save
      redirect_to admin_genres_path
    else
      @genre=Genre.new
      @genres=Genre.all
      render :index
    end
  end

  def edit
    @genre=Genre.find(params[:id])
  end

  def update
    genre=Genre.find(params[:id])
    if genre.update(genre_params)
      redirect_to admin_genres_path
    else
      @genre=Genre.find(params[:id])
      render :edit
    end
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @orders=Order.page(params[:page]).reverse_order
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @items=Item.page(params[:page]).reverse_order
  end

  def new
    @item=Item.new
    @genres=Genre.all
  end

  def create
    item=Item.new(item_params)
    if item.save
      redirect_to admin_item_path(item)
    else
      @item=Item.new
      @genres=Genre.all
      render :new
    end
  end

  def show
    @item=Item.find(params[:id])
    @genre=@item.genre
  end

  def edit
    @item=Item.find(params[:id])
    @genres=Genre.all
  end

  def update
    item=Item.find(params[:id])
    if item.update(item_params)
      redirect_to admin_item_path
    else
      @item=Item.find(params[:id])
      @genres=Genre.all
      render :edit
    end
  end

  private
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @order=Order.find(params[:id])
  end

  def update
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  protected
    def after_sign_in_path_for(resource)
      admin_path
    end

    def after_sign_out_path_for(resource)
      new_admin_session_path
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

#ログイン後の遷移先
  def after_sign_in_path_for(resource)
    if customer_signed_in?
      customers_my_page_path(resource.id)
    else
      admin_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_active])
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_details_helper.rb
module OrdersDetailsHelper
end

app/views/admin/genres/edit.html.erb
<main>
  <div class="container">
    <% if @genre.errors.any? %>
      <%= @genre.errors.count %>件のエラーが発生しました
      <% @genre.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
    <% end %>
    <h3>ジャンル編集</h3>
    <%= form_with model:@genre,url: admin_genre_path, local:true do |f| %>
      <%= f.label :ジャンル名 %>
      <%= f.text_field :name %>
      <%= f.submit '変更を保存', class: "btn btn-success" %>
    <%end%>
  </div>
</main>

app/views/admin/genres/index.html.erb
<main>
  <div class="container">
    <% if @genre.errors.any? %>
      <%= @genre.errors.count %>件のエラーが発生しました
      <% @genre.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
    <% end %>
    <h3>ジャンル一覧・追加</h3>
    <%= form_with model:@genre,url: admin_genres_path, local:true do |f| %>
      <%= f.label :ジャンル名 %>
      <%= f.text_field :name %>
      <%= f.submit '新規登録', class: "btn btn-success" %>
    <%end%>
    <table class="table">
      <tr>
        <th>ジャンル</th>
      </tr>
      <%@genres.each do |genre|%>
      <tr>
        <td>
          <%=genre.name%>
          <%= link_to '編集する',edit_admin_genre_path(genre.id), class: "btn btn-success"%>
        </td>
      </tr>
      <%end%>
    </table>
  </div>
</main>

app/views/admin/items/edit.html.erb
<main>
  <div class="container">
    <h3>商品編集</h3>
    <%=form_with model:@item,url: admin_item_path, local:true do |f| %>
      <table class="table table-borderless">
        <tr>
          <th>
            商品画像
          </th>
          <td>
            <%= f.attachment_field :image %>
          </td>
        </tr>
        <tr>
          <th>
            商品名
          </th>
          <td>
            <%= f.text_field :name %>
          </td>
        </tr>
        <tr>
          <th>
            商品説明
          </th>
          <td>
            <%= f.text_area :introduction %>
          </td>
        </tr>
        <tr>
          <th>
            ジャンル
          </th>
          <td>
            <%= f.collection_select(:genre_id, @genres, :id, :name, {prompt: "選択してください"}) %>
          </td>
        </tr>
        <tr>
          <th>
            税抜価格
          </th>
          <td>
            <%= f.text_field :price %>円
          </td>
        </tr>
        <tr>
          <th>
            販売ステータス
          </th>
          <td>
            -
          </td>
        </tr>
      </table>
      <%= f.submit '変更を保存', class:"btn btn-success" %>
    <%end%>
  </div>
</main>

app/views/admin/items/index.html.erb
<main>
  <div class="container">
    <h3>商品一覧</h3>
    <a href="/admin/items/new">
      <i class="fas fa-plus fa-2x"></i>
    </a>
    <table class="table">
      <tr>
        <td>
          商品ID
        </td>
        <td>
          商品名
        </td>
        <td>
          税抜価格
        </td>
        <td>
          ジャンル
        </td>
        <td>
          ステータス
        </td>
      </tr>
      <%@items.each do |item|%>
      <tr>
        <td>
          <%=item.id%>
        </td>
        <td>
          <%=link_to admin_item_path(item.id) do %><%=item.name%><%end%>
        </td>
        <td>
          <%=item.price%>
        </td>
        <td>
          <%=item.genre.name%>
        </td>
        <td>
          -
        </td>
      </tr>
      <%end%>
    </table>
    <%= paginate @items %>
  </div>
</main>

app/views/admin/items/new.html.erb
<main>
  <div class="container">
    <% if @item.errors.any? %>
      <%= @item.errors.count %>件のエラーが発生しました
      <% @item.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
    <% end %>
    <h2>商品新規登録</h2>
    <%= form_with model:@item, url:admin_items_path, local:true do |f| %>
      <table class="table table-borderless">
        <tr>
          <th>
            商品画像
          </th>
          <td>
            <%= f.attachment_field :image %>
          </td>
        </tr>
        <tr>
          <th>
            商品名
          </th>
          <td>
            <%= f.text_field :name %>
          </td>
        </tr>
        <tr>
          <th>
            商品説明
          </th>
          <td>
            <%= f.text_area :introduction %>
          </td>
        </tr>
        <tr>
          <th>
            ジャンル
          </th>
          <td>
            <%= f.collection_select(:genre_id, @genres, :id, :name, {prompt: "選択してください"}) %>
          </td>
        </tr>
        <tr>
          <th>
            税抜価格
          </th>
          <td>
            <%= f.text_field :price %>円
          </td>
        </tr>
        <tr>
          <th>
            販売ステータス
          </th>
          <td>
            -
          </td>
        </tr>
      </table>
      <%= f.submit '新規登録', class:"btn btn-success" %>
    <%end%>
  </div>
</main>

app/views/admin/items/show.html.erb
<main>
  <div class="container">
    <h3>商品詳細</h3>
    <%= attachment_image_tag @item, :image %>
    <table class="table table-borderless">
      <tr>
        <th>
          商品名
        </th>
        <td>
          <%= @item.name %>
        </td>
      </tr>
      <tr>
        <th>
          商品説明
        </th>
        <td>
          <%= @item.introduction %>
        </td>
      </tr>
      <tr>
        <th>
          ジャンル
        </th>
        <td>
          <%= @genre.name %>
        </td>
      </tr>
      <tr>
        <th>
          税込価格(税抜価格)
        </th>
        <td>
          <%= @item.add_tax_price.to_s(:delimited) %>(<%= @item.price %>)円
        </td>
      </tr>
      <tr>
        <th>
          販売ステータス
        </th>
        <td>
          -
        </td>
      </tr>
    </table>
    <%= link_to '編集する',edit_admin_item_path, class:"btn btn-success" %>
  </div>
</main>

app/views/admin/orders/show.html.erb
<main>
  <div class="container">
    <h3>注文履歴詳細</h3>
    <div class="row">
      <table>
        <tr>
          <th>購入者</th>
          <td><%= @order.customer.first_name%><%= @order.customer.last_name%></td>
        </tr>
        <tr>
          <th>注文日</th>
          <td><%= @order.created_at.strftime('%Y/%m/%d')%></td>
        </tr>
        <tr>
          <th>配送先</th>
          <td>〒<%= @order.postal_code%><%= @order.address%><%= @order.name%></td>
        </tr>
        <tr>
          <th>支払方法</th>
          <td><%= @order.payment_method%></td>
        </tr>
        <tr>
          <th>注文ステータス</th>
          <td>-<%= link_to'更新', admin_order_path, class: "btn btn-success"%></td>
        </tr>
      </table>
    </div>
    <% @sum=0 %>
    <div class="row">
      <table class="table">
        <tr>
          <th>商品名</th>
          <th>単価(税込)</th>
          <th>数量</th>
          <th>小計</th>
          <th>製作ステータス</th>
          <th></th>
        </tr>
        <%@order.order_details.each do |order_detail| %>
          <tr>
            <td><%= order_detail.item.name%></td>
            <td><%= order_detail.item.price.to_s(:delimited)%></td>
            <td><%= order_detail.amount %></td>
            <td><%= (order_detail.item.price*order_detail.amount).to_s(:delimited)%></td>
            <% @sum+=order_detail.item.price*order_detail.amount%>
            <td>-</td>
            <td><%= link_to'更新', admin_order_path, class: "btn btn-success"%></td>
          </tr>
        <%end%>
      </table>
      <table>
        <tr>
          <th>商品合計</th>
          <td><%= @sum.to_s(:delimited) %>円</td>
        </tr>
        <tr>
          <th>送料</th>
          <td><%=800%>円</td>
        </tr>
        <tr>
          <th>請求金額合計</th>
          <td><%= (@sum+800).to_s(:delimited)%>円</td>
        </tr>
      </table>
    </div>
  </div>
</main>