config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: :all
  devise_scope :customer do
    get '/customers/sign_up' => 'public/registrations#new'
    post '/customers' => 'public/registrations#create'
    get '/customers/sign_in' => 'public/sessions#new'
    post '/customers/sign_in' => 'public/sessions#create'
    delete '/customers/sign_out' => 'public/sessions#destroy'
    patch '/customers/withdraw' => 'public/customers#withdraw'
  end

  devise_for :admin, controllers: {
    sessions: 'admin/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

# Admin
  get '/admin', to: 'admin/homes#top'

  namespace :admin do
    resources :items, except: [:destroy]
  end

  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update]
  end

  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
  end

# できたらやる
  namespace :admin do
    resources :orders, only: [:show, :update]
  end

  namespace :admin do
    get '/orders/:order_details/:id', to: 'admin/order_details#update'
  end

# 会員
  root to:'public/homes#top'
  get '/about', to:'public/homes#about'

  resources :items, only: [:index, :show], to: 'public/items#'

  resource :customers, only: [:edit, :update], to: 'public/customers#'
  get '/customers/my_page', to:'public/customers#show'
  get '/customers/unsubscribe', to:'public/customers#unsubscribe'

  delete '/cart_items/destroy_all', to:'public/cart_items#destroy_all'
  resources :cart_items, only: [:index, :update, :destroy, :create], to: 'public/cart_items#'

  get '/orders/complete', to: 'public/orders#complete'
  post '/orders/confirm', to: 'public/orders#confirm'
  resources :orders, only: [:new, :create, :index, :show], to: 'public/orders#'

  resources :addresses, except: [:show, :new], to: 'public/addresses#'

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def full_address
    postal_code + address + name
  end

  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  def active_for_authentication?
    super && (self.is_active == true)
  end

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name_kana, presence: true
  validates :last_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
  validates :email, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre

  attachment :image

  validates :image, presence: true
  validates :name, presence: true
  validates :introduction, presence: true
  validates :genre_id, presence: true
  validates :price, presence: true


  def add_tax_price
    (self.price * 1.10).round
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum payment_method: { "クレジットカード": 0, "銀行振込": 1 }
  enum order_status: {"入金待ち": 0,"入金確認": 1,"製作中": 2,"発送準備中": 3, "発送済み": 4}

	def cart_items
		cart.line_items.each do |item|
			item.cart_item_id = nil
			line_items << item
		end
	end

	validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true
  validates :payment_method, presence: true

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item


end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @orders=Order.page(params[:page]).reverse_order
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @items=Item.page(params[:page]).reverse_order
  end

  def new
    @item=Item.new
    @genres=Genre.all
  end

  def create
    item=Item.new(item_params)
    if item.save
      redirect_to admin_item_path(item)
    else
      @item=Item.new
      @genres=Genre.all
      render :new
    end
  end

  def show
    @item=Item.find(params[:id])
    @genre=@item.genre
  end

  def edit
    @item=Item.find(params[:id])
    @genres=Genre.all
  end

  def update
    item=Item.find(params[:id])
    if item.update(item_params)
      redirect_to admin_item_path
    else
      @item=Item.find(params[:id])
      @genres=Genre.all
      render :edit
    end
  end

  private
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

#ログイン後の遷移先
  def after_sign_in_path_for(resource)
    if customer_signed_in?
      customers_my_page_path(resource.id)
    else
      admin_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_active])
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_details_helper.rb
module OrdersDetailsHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <%= content_tag :div, value, class: "#{key}" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NAGANOCAKE</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/454b157adc.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="border-bottom">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a href='/'>
          <%= image_tag 'logomark.jpg',  class:"logomark" %>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <div class="container">
              <div class="row">
                <%if customer_signed_in?%>
                　<div class="col">
                    <li>
                      ようこそ、<%= current_customer.first_name%>さん！
                    </li>
                  </div>
                  <div class="col my-2">
                    <li>
                      <%= link_to 'マイページ', customers_my_page_path, class: "btn btn-outline-secondary" %>
                    </li>
                  </div>
                  <div class="col my-2">
                    <li>
                      <%= link_to '商品一覧', items_path, class: "btn btn-outline-secondary" %>
                    </li>
                  </div>
                  <div class="col my-2">
                    <li>
                      <%= link_to 'カート', cart_items_path, class: "btn btn-outline-secondary" %>
                    </li>
                  </div>
                  <div class="col my-2">
                    <li>
                      <%= link_to 'ログアウト', customers_sign_out_path, method: :delete, class: "btn btn-outline-secondary" %>
                    </li>
                  </div>
                <%elsif admin_signed_in?%>
                  <div class="col my-2">
                    <li>
                      <%= link_to '商品一覧', admin_items_path, class: "btn btn-outline-secondary" %>
                    </li>
                  </div>
                  <div class="col my-2">
                    <li>
                      <%= link_to '会員一覧', admin_customers_path, class: "btn btn-outline-secondary" %>
                    </li>
                  </div>
                  <div class="col my-2">
                    <li>
                      <%= link_to '注文履歴一覧', admin_path, class: "btn btn-outline-secondary" %>
                    </li>
                  </div>
                  <div class="col my-2">
                    <li>
                      <%= link_to 'ジャンル一覧', admin_genres_path, class: "btn btn-outline-secondary" %>
                    </li>
                  </div>
                  <div class="col my-2">
                    <li>
                      <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: "btn btn-outline-secondary" %>
                    </li>
                  </div>
                  <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search未実装" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                  </form>
                <%else%>
                  <div class="col my-2">
                    <li>
                      <%= link_to 'About', about_path, class: "btn btn-outline-secondary" %>
                    </li>
                  </div>
                  <div class="col my-2">
                    <li>
                      <%= link_to '商品一覧', items_path, class: "btn btn-outline-secondary" %>
                    </li>
                  </div>
                  <div class="col my-2">
                    <li>
                      <%= link_to '新規登録', customers_sign_up_path, class: "btn btn-outline-secondary" %>
                    </li>
                  </div>
                  <div class="col my-2">
                    <li>
                      <%= link_to 'ログイン', customers_sign_in_path, class: "btn btn-outline-secondary" %>
                    </li>
                  </div>
                <%end%>
              </div>
            </div>
          </ul>
        </div>
      </nav>
    </header>
    <%= render 'layouts/flash'%>
    <%= yield %>
    <footer class="border-top"></footer>
  </body>
</html>